"""creating tables

Revision ID: 10246ea94e51
Revises: ac7d559c5e24
Create Date: 2021-06-11 20:42:28.444945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10246ea94e51'
down_revision = 'ac7d559c5e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('test_column', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'test_column')
    # ### end Alembic commands ###
