"""creating tables

Revision ID: aa704d2856eb
Revises: b39377eb25dc
Create Date: 2021-06-08 14:22:04.901425

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'aa704d2856eb'
down_revision = 'b39377eb25dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations_users',
    sa.Column('conversationId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversationId'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('conversationId', 'userId')
    )
    op.add_column('messages', sa.Column('conversationId', sa.Integer(), nullable=True))
    op.drop_constraint('messages_recieverId_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversationId'], ['id'])
    op.drop_column('messages', 'recieverId')

    if environment == "production":
        op.execute(f"ALTER TABLE conversations SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('recieverId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_recieverId_fkey', 'messages', 'users', ['recieverId'], ['id'])
    op.drop_column('messages', 'conversationId')
    op.drop_table('conversations_users')
    op.drop_table('conversations')
    # ### end Alembic commands ###
