"""creating tables

Revision ID: ac7d559c5e24
Revises: a9f5cedf54c9
Create Date: 2021-06-11 20:29:59.286201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac7d559c5e24'
down_revision = 'a9f5cedf54c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('settings', sa.Text(), nullable=False))
    op.drop_column('messages', 'reflector_settings')
    op.drop_column('messages', 'selfDestructDate')
    op.drop_column('messages', 'rotor_settings')
    op.drop_column('messages', 'plugboard_settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('plugboard_settings', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('rotor_settings', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('selfDestructDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('reflector_settings', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'settings')
    # ### end Alembic commands ###
